version: '3.9'

services:
  # MongoDB service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - "2717:27017"
    volumes:
      - mongo_db:/data/db

  # Node.js API service
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:3000"
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongo_db:27017
      DB_NAME: datarecords
      NAME: dawg
    depends_on:
      - mongo_db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  mongo_db: {}
